import type { PokedexPageContent } from './PokedexPage';

export const PAGES_DATA: PokedexPageContent[] = [
    {
        pageId: 'page1',
        items: [
            {
                id: 'p1_item1',
                name: 'フラワー 1',
                largeImage: require(`@/assets/images/character/a-tisuto/a-tisuto_1.png`),
                description1: 'これはフラワー 1 の説明1です。',
                description2: '色や形に特徴があります。',
                description3: '開花時期は春です。',
                smallIcon: require('@/assets/images/character/a-tisuto/a-tisuto_1.png'),
            },
            {
                id: 'p1_item2',
                name: 'フラワー 2',
                largeImage: require(`@/assets/images/character/a-tisuto/a-tisuto_2.png`),
                description1: 'これはフラワー 2 の説明1です。',
                description2: '色や形に特徴があります。',
                description3: '開花時期は春です。',
                smallIcon: require('@/assets/images/character/a-tisuto/a-tisuto_2.png'),
            },
            {
                id: 'p1_item3',
                name: 'フラワー 3',
                largeImage: require(`@/assets/images/character/a-tisuto/a-tisuto_3.png`),
                description1: 'これはフラワー 3 の説明1です。',
                description2: '色や形に特徴があります。',
                description3: '開花時期は春です。',
                smallIcon: require('@/assets/images/character/a-tisuto/a-tisuto_3.png'),
            },
            {
                id: 'p1_item4',
                name: 'フラワー 4',
                largeImage: require(`@/assets/images/character/a-tisuto/a-tisuto_4.png`),
                description1: 'これはフラワー 4 の説明1です。',
                description2: '色や形に特徴があります。',
                description3: '開花時期は春です。',
                smallIcon: require('@/assets/images/character/a-tisuto/a-tisuto_4.png'),
            },
            {
                id: 'p1_item5',
                name: 'フラワー 5',
                largeImage: require(`@/assets/images/character/amiodaron/amiodaron_1.png`),
                description1: 'これはフラワー 5 の説明1です。',
                description2: '色や形に特徴があります。',
                description3: '開花時期は春です。',
                smallIcon: require('@/assets/images/character/amiodaron/amiodaron_1.png'),
            },
            {
                id: 'p1_item6',
                name: 'フラワー 6',
                largeImage: require(`@/assets/images/character/amiodaron/amiodaron_2.png`),
                description1: 'これはフラワー 6 の説明1です。',
                description2: '色や形に特徴があります。',
                description3: '開花時期は春です。',
                smallIcon: require('@/assets/images/character/amiodaron/amiodaron_1.png'),
            },
            {
                id: 'p1_item7',
                name: 'フラワー 7',
                largeImage: require(`@/assets/images/character/amiodaron/amiodaron_3.png`),
                description1: 'これはフラワー 7 の説明1です。',
                description2: '色や形に特徴があります。',
                description3: '開花時期は春です。',
                smallIcon: require('@/assets/images/character/amiodaron/amiodaron_1.png'),
            },
            {
                id: 'p1_item8',
                name: 'フラワー 8',
                largeImage: require(`@/assets/images/character/amiodaron/amiodaron_4.png`),
                description1: 'これはフラワー 8 の説明1です。',
                description2: '色や形に特徴があります。',
                description3: '開花時期は春です。',
                smallIcon: require('@/assets/images/character/amiodaron/amiodaron_1.png'),
            },
        ],
    },
    {
        pageId: 'page2',
        items: [
            {
                id: 'p2_item1',
                name: 'ハーブ 1',
                largeImage: require('@/assets/images/character/jigokisin/jigokisin_1.png'),
                description1: 'これはハーブ 1 の説明1です。',
                description2: '薬効成分が含まれています。',
                description3: '主に夏に収穫されます。',
                smallIcon: require('@/assets/images/character/amiodaron/amiodaron_1.png'),
            },
            {
                id: 'p2_item2',
                name: 'ハーブ 2',
                largeImage: require('@/assets/images/character/jigokisin/jigokisin_2.png'),
                description1: 'これはハーブ 2 の説明1です。',
                description2: '薬効成分が含まれています。',
                description3: '主に夏に収穫されます。',
                smallIcon: require('@/assets/images/character/amiodaron/amiodaron_1.png'),
            },
            {
                id: 'p2_item3',
                name: 'ハーブ 3',
                largeImage: require('@/assets/images/character/jigokisin/jigokisin_3.png'),
                description1: 'これはハーブ 3 の説明1です。',
                description2: '薬効成分が含まれています。',
                description3: '主に夏に収穫されます。',
                smallIcon: require('@/assets/images/character/amiodaron/amiodaron_1.png'),
            },
            {
                id: 'p2_item4',
                name: 'ハーブ 4',
                largeImage: require('@/assets/images/character/jigokisin/jigokisin_4.png'),
                description1: 'これはハーブ 4 の説明1です。',
                description2: '薬効成分が含まれています。',
                description3: '主に夏に収穫されます。',
                smallIcon: require('@/assets/images/character/amiodaron/amiodaron_1.png'),
            },
            {
                id: 'p2_item5',
                name: 'ハーブ 5',
                largeImage: require('@/assets/images/character/rasikkusu/rasikkusu_1.png'),
                description1: 'これはハーブ 5 の説明1です。',
                description2: '薬効成分が含まれています。',
                description3: '主に夏に収穫されます。',
                smallIcon: require('@/assets/images/character/amiodaron/amiodaron_1.png'),
            },
            {
                id: 'p2_item6',
                name: 'ハーブ 6',
                largeImage: require('@/assets/images/character/rasikkusu/rasikkusu_2.png'),
                description1: 'これはハーブ 6 の説明1です。',
                description2: '薬効成分が含まれています。',
                description3: '主に夏に収穫されます。',
                smallIcon: require('@/assets/images/character/amiodaron/amiodaron_1.png'),
            },
            {
                id: 'p2_item7',
                name: 'ハーブ 7',
                largeImage: require('@/assets/images/character/rasikkusu/rasikkusu_3.png'),
                description1: 'これはハーブ 7 の説明1です。',
                description2: '薬効成分が含まれています。',
                description3: '主に夏に収穫されます。',
                smallIcon: require('@/assets/images/character/amiodaron/amiodaron_1.png'),
            },
            {
                id: 'p2_item8',
                name: 'ハーブ 8',
                largeImage: require('@/assets/images/character/rasikkusu/rasikkusu_4.png'),
                description1: 'これはハーブ 8 の説明1です。',
                description2: '薬効成分が含まれています。',
                description3: '主に夏に収穫されます。',
                smallIcon: require('@/assets/images/character/amiodaron/amiodaron_1.png'),
            },
        ],
    },
];